export const cartTypes = {
  TOGGLE_CART_HIDDEN: 'TOGGLE_CART_HIDDEN',
  ADD_ITEM: 'ADD_ITEM',
  REMOVE_ITEM: 'REMOVE_ITEM',
  REMOVE_ALL_OF_TYPE: 'REMOVE_ALL_OF_TYPE',
  CLEAR_CART: 'CLEAR_CART',
  SET_CART_FROM_FIREBASE: 'SET_CART_FROM_FIREBASE',
};